---
- name: Taiga Logs folder
  file: path={{ taiga_path }}/logs state=directory
  sudo: yes
  sudo_user: taiga

- name: Taiga Init folder
  file: path=/etc/init state=directory
  sudo: yes

- pip: name={{item}}
  sudo: yes
  with_items:
    - circus

- name: Circus ini config file
  template: src=circus.ini dest={{ taiga_path }}/circus.ini owner=taiga group=taiga
  sudo: yes
  sudo_user: taiga

- name: Circus init file
  template: src=circus.service dest=/etc/systemd/system/circus.service owner=root group=root
  sudo: yes
  notify:
    - Start Circus

- meta: flush_handlers
