---
- name: Install Nginx Packages
  yum: name=nginx state=latest
  sudo: yes
  notify:
    - Start Nginx

- name: Taiga Nginx Configuration
  template: src=taiga.conf dest=/etc/nginx/conf.d/taiga.conf owner=root group=root
  sudo: yes

- name: SElinux Packages
  yum: name={{ item }} state=latest
  sudo: yes
  with_items:
    - policycoreutils
    - policycoreutils-python
    - libselinux
    - libselinux-utils

- name: Firewall rules for http
  shell: firewall-cmd --permanent --add-service {{ scheme }}
  sudo: yes
  notify:
    - Firewall Reload

- name: Selinux context for Taiga
  shell: semanage fcontext -a -t httpd_sys_content_t "/home/taiga(/.*)?"
  sudo: yes

- name: Selinux context for Taiga Logs
  shell: semanage fcontext -a -t var_log_t "/home/taiga/logs(/.*)?"
  sudo: yes
  notify:
    - Selinux Taiga Restore

- meta: flush_handlers
