# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

# User specific environment and startup programs

PATH={{PATH}}
LD_LIBRARY_PATH={{LD_LIBRARY_PATH}}

export LD_LIBRARY_PATH
export PATH