---
- name: Selinux Taiga Restore
  shell: restorecon -vvFR {{ taiga_path }}
  sudo: yes

- name: Firewall Reload
  shell: firewall-cmd --reload
  sudo: yes


- name: Start Circus
  shell: /bin/circusd --daemon /home/taiga/circus.ini
  sudo: yes
  sudo_user: taiga

#- name: Start Circus
#  service: name=circus state=started enabled=yes
#  sudo: yes

- name: Start Nginx
  service: name=nginx state=started enabled=yes
  sudo: yes
