---
- name: Taiga Settings file
  template: src=local.py dest={{ backend_path }}/settings/local.py owner=taiga group=taiga
  sudo: yes

- name: Migrate Taiga DB
  django_manage: >
    command=migrate
    app_path={{ backend_path }}
    virtualenv={{ virtualenv_dir }}
  sudo: yes
  sudo_user: taiga

- name: Installing fixtures into Taiga DB
  django_manage: >
    command=loaddata 
    app_path={{ backend_path }} 
    fixtures={{ item }}
    virtualenv={{ virtualenv_dir }}
  with_items:
    - initial_user
    - initial_project_templates
    - initial_role 
  sudo: yes
  sudo_user: taiga

- name: Making statics for Taiga Backend
  django_manage: >
    command=collectstatic 
    app_path={{ backend_path }}
    virtualenv={{ virtualenv_dir }}
  sudo: yes
  sudo_user: taiga
